packages:
  - packages/*
  - apps/*

allowBuilds:
  esbuild: true
  '@parcel/watcher': true

catalog:
  '@storybook/addon-a11y': 10.4.6
  '@storybook/addon-docs': 10.4.6
  '@storybook/react-vite': 10.4.6
  '@types/node': ^24.12.0
  '@types/react': ^19
  '@types/react-dom': ^19
  '@vitejs/plugin-react': ^6.0.3
  astro: ^7.3.5
  react: 19.2.4
  react-dom: 19.2.4
  sass: ^1.105.0
  storybook: 10.4.6
  typescript: 6.0.2
  vite: ^8.0.0
  vitest: 5.0.1

minimumReleaseAgeExclude:
  - astro@7.3.5
