// Generates the entry files and package exports from src/components, so adding a part needs no manual wiring.
// Run with --check to fail when the committed files are out of date.
import { readdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { themeIds } from '../src/config.ts'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const check = process.argv.includes('--check')

const families = (await readdir(join(root, 'src/components'), { withFileTypes: true }))
  .filter((d) => d.isDirectory())
  .map((d) => d.name)
  .sort()

const astro: Record<string, string> = {}
for (const family of families) {
  for (const file of (await readdir(join(root, 'src/components', family))).sort()) {
    if (!file.endsWith('.astro')) {
      continue
    }
    const name = file.replace(/\.astro$/, '')
    if (astro[name]) {
      throw new Error(`Duplicate component name "${name}" in ${family} and ${astro[name]}`)
    }
    astro[name] = family
  }
}

const header = '// Generated by scripts/generate.ts. Do not edit.\n'
const pascal = (name: string) => name.replace(/(^|-)([a-z])/g, (_m, _d, c: string) => c.toUpperCase())
const astroBarrel = Object.entries(astro)
  .map(([name, family]) => `export { default as ${pascal(name)} } from './components/${family}/${name}.astro'\n`)
  .join('')
const files: Record<string, string> = {
  'src/parts.ts': `${header}${families.map((f) => `export * from './components/${f}/index.ts'\n`).join('')}export * from './config.ts'\n`,
  'src/react.ts': `${header}export * from './parts.ts'\n${families.map((f) => `export * from './components/${f}/${f}.tsx'\n`).join('')}`,
  'src/astro.ts': `${header}${astroBarrel}`,
  'src/styles/themes.scss': `${header}// Every theme in one file, for docs and previews that switch themes with data-x-theme. Sites load one theme.\n@use 'sass:meta';\n\n${themeIds.map((t) => `@include meta.load-css('themes/${t}');\n`).join('')}`,
  'src/styles/all.scss': `${header.replace('//', '//')}@use 'sass:meta';\n\n${families.map((f) => `@include meta.load-css('../components/${f}/${f}');\n`).join('')}`,
}
for (const theme of themeIds) {
  files[`src/styles/themes/_${theme}-parts.scss`] =
    `${header}@use 'sass:meta';\n\n${families.map((f) => `@include meta.load-css('../../components/${f}/${f}.${theme}');\n`).join('')}`
}

const pkgPath = join(root, 'package.json')
const pkg = JSON.parse(await readFile(pkgPath, 'utf8'))
const exports: Record<string, unknown> = {}
for (const theme of themeIds) {
  exports[`./themes/${theme}.css`] = {
    source: `./src/styles/themes/${theme}.scss`,
    default: `./dist/themes/${theme}.css`,
  }
}
exports['./themes.css'] = { source: './src/styles/themes.scss', default: './dist/themes.css' }
exports['./all.css'] = { source: './src/styles/all.scss', default: './dist/all.css' }
exports['./scss/*'] = './src/styles/*'
exports['./astro'] = { source: './src/astro.ts', types: './dist/astro.d.ts', default: './dist/astro.js' }
for (const entry of ['parts', 'react']) {
  exports[`./${entry}`] = {
    source: `./src/${entry}.ts`,
    types: `./dist/${entry}.d.ts`,
    import: `./dist/${entry}.js`,
  }
}
for (const [name, family] of Object.entries(astro)) {
  exports[`./astro/${name}`] = {
    source: `./src/components/${family}/${name}.astro`,
    default: `./dist/components/${family}/${name}.astro`,
  }
}
files['package.json'] = `${JSON.stringify({ ...pkg, exports }, null, 2)}\n`

let stale = 0
for (const [path, content] of Object.entries(files)) {
  const full = join(root, path)
  const current = await readFile(full, 'utf8').catch(() => '')
  if (current === content) {
    continue
  }
  if (check) {
    console.error(`Out of date: ${path}. Run pnpm --filter @xaroth.nl/design generate.`)
    stale++
  } else {
    await writeFile(full, content)
  }
}
if (stale) {
  process.exit(1)
}
